name: Update Lists

on:
  schedule:
    - cron: '* * * * *'
  push:
    paths:
      - 'list_generator.py'
  pull_request:
    paths:
      - 'list_generator.py'
  workflow_dispatch:

jobs:
  update-lists:
    runs-on: ubuntu-latest
    env:
      python: 3.7
      dnspython: 2.1.0
    
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python }}
        
      - name: Check Python3 Version
        run: python3 --version
      
      - name: Installing dnspython-${{ env.dnspython }}
        run: sudo pip3 install -I dnspython==${{ env.dnspython }}
      
      - name: Generating Lists
        run: python3 ./list_generator.py
      
      - name: Commit changes
        run: |
          git config --local user.email '46617994+touhidurrr@users.noreply.github.com'
          git config --local user.name 'touhidurrr'
          git add *.txt
          git commit -m "Updated Lists"
          git push
