name: Update Lists

on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    paths:
      - '**.py'
      - '.github/workflows/update_lists.yml'
  pull_request:
    paths:
      - '**.py'
      - '.github/workflows/update_lists.yml'
  workflow_dispatch:

jobs:
  update-lists:
    runs-on: ubuntu-latest
    env:
      python: '3.10.0-rc.2'
      dnspython: '2.1.0'

    steps:
      - uses: actions/checkout@main
        with:
          token: ${{ secrets.PAT }}

      - name: Setup Python
        uses: actions/setup-python@main
        with:
          python-version: ${{ env.python }}

      - name: Check Python3 Version
        run: python3 --version

      - name: Installing dnspython-${{ env.dnspython }} and Generating Lists
        run: |
          pip3 install --upgrade pip
          pip3 install -I dnspython==${{ env.dnspython }}
          python3 ./list_generator.py

      - name: Commit changes
        run: |
          git config --local user.email '46617994+touhidurrr@users.noreply.github.com'
          git config --local user.name 'touhidurrr'
          git add ipv?_list.txt
          git commit -m 'Updated Lists [Automated]'
          git pull
          git push
